Universe           = vanilla
Initialdir         = /sphenix/user/hjheng/TrackletAna/analysis
Executable         = $(Initialdir)/TrackletAna_RecoVtx_condor.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 15GB
Priority           = 20
job_lease_duration = 3600
isdata             = ISDATA
dphicut            = DPHICUT
dzcut              = DZCUT
gapnorth           = GAPNORTH
gapupper           = GAPUPPER
centshift          = CENTSHIFT
Output             = $(Initialdir)/condor_RecoVtx/condor_out/out/condor_dphicutDPHICUT_dzcutDZCUT_gapnorthGAPNORTH_gapupperGAPUPPER_centshiftCENTSHIFT.out
Error              = $(Initialdir)/condor_RecoVtx/condor_out/err/condor_dphicutDPHICUT_dzcutDZCUT_gapnorthGAPNORTH_gapupperGAPUPPER_centshiftCENTSHIFT.err
Log                = $(Initialdir)/condor_RecoVtx/condor_out/log/condor_dphicutDPHICUT_dzcutDZCUT_gapnorthGAPNORTH_gapupperGAPUPPER_centshiftCENTSHIFT.log
Arguments          = $(isdata) $(dphicut) $(dzcut) $(gapnorth) $(gapupper) $(centshift)
Queue 1