#! /usr/bin/env python
from optparse import OptionParser
import sys
import os
import datetime
from array import *
from ROOT import *
import numpy
import math
import glob
from plotUtil import *

gROOT.LoadMacro('./sPHENIXStyle/sPhenixStyle.C')
gROOT.ProcessLine('SetsPhenixStyle()')
gROOT.SetBatch(True)

if __name__ == '__main__':
    parser = OptionParser()
    parser.add_option("-f", "--file", dest="filename",help="histogram file path")
    (options, args) = parser.parse_args()
    if not options.filename:
        parser.error("please give an input histogram file")

    plotpath = './RecoClusters/'
    os.makedirs(plotpath, exist_ok=True)
    
    histfname = options.filename

    hM_ClusZ_all = GetHistogram(histfname, 'hM_ClusZ_all')
    hM_ClusZ_layer1 = GetHistogram(histfname, 'hM_ClusZ_layer1')
    hM_ClusZ_layer2 = GetHistogram(histfname, 'hM_ClusZ_layer2')
    hM_ClusZ_layer3 = GetHistogram(histfname, 'hM_ClusZ_layer3')
    hM_ClusEtaPV_all = GetHistogram(histfname, 'hM_ClusEtaPV_all')
    hM_ClusEtaPV_layer1 = GetHistogram(histfname, 'hM_ClusEtaPV_layer1')
    hM_ClusEtaPV_layer2 = GetHistogram(histfname, 'hM_ClusEtaPV_layer2')
    hM_ClusEtaPV_layer3 = GetHistogram(histfname, 'hM_ClusEtaPV_layer3')
    hM_ClusEtaOri_all = GetHistogram(histfname, 'hM_ClusEtaOri_all')
    hM_ClusEtaOri_layer1 = GetHistogram(histfname, 'hM_ClusEtaOri_layer1')
    hM_ClusEtaOri_layer2 = GetHistogram(histfname, 'hM_ClusEtaOri_layer2')
    hM_ClusEtaOri_layer3 = GetHistogram(histfname, 'hM_ClusEtaOri_layer3')
    hM_ClusPhi_all = GetHistogram(histfname, 'hM_ClusPhi_all')
    hM_ClusPhi_layer1 = GetHistogram(histfname, 'hM_ClusPhi_layer1')
    hM_ClusPhi_layer2 = GetHistogram(histfname, 'hM_ClusPhi_layer2')
    hM_ClusPhi_layer3 = GetHistogram(histfname, 'hM_ClusPhi_layer3')
    hM_ClusADC_all = GetHistogram(histfname, 'hM_ClusADC_all')
    hM_ClusADC_layer1 = GetHistogram(histfname, 'hM_ClusADC_layer1')
    hM_ClusADC_layer2 = GetHistogram(histfname, 'hM_ClusADC_layer2')
    hM_ClusADC_layer3 = GetHistogram(histfname, 'hM_ClusADC_layer3')
    hM_ClusZSize_all = GetHistogram(histfname, 'hM_ClusZSize_all')
    hM_ClusZSize_layer1 = GetHistogram(histfname, 'hM_ClusZSize_layer1')
    hM_ClusZSize_layer2 = GetHistogram(histfname, 'hM_ClusZSize_layer2')
    hM_ClusZSize_layer3 = GetHistogram(histfname, 'hM_ClusZSize_layer3')
    hM_ClusPhiSize_all = GetHistogram(histfname, 'hM_ClusPhiSize_all')
    hM_ClusPhiSize_layer1 = GetHistogram(histfname, 'hM_ClusPhiSize_layer1')
    hM_ClusPhiSize_layer2 = GetHistogram(histfname, 'hM_ClusPhiSize_layer2')
    hM_ClusPhiSize_layer3 = GetHistogram(histfname, 'hM_ClusPhiSize_layer3')
    hM_ClusPairDr_layer1 = GetHistogram(histfname, 'hM_ClusPairDr_layer1')
    hM_ClusPairDr_layer2 = GetHistogram(histfname, 'hM_ClusPairDr_layer2')
    hM_ClusPairDr_layer3 = GetHistogram(histfname, 'hM_ClusPairDr_layer3')

    hM_ClusX_ClusY_all = GetHistogram(histfname, 'hM_ClusX_ClusY_all')
    hM_ClusZ_ClusPhi_all = GetHistogram(histfname, 'hM_ClusZ_ClusPhi_all')
    hM_ClusZ_ClusPhi_layer1 = GetHistogram(histfname, 'hM_ClusZ_ClusPhi_layer1')
    hM_ClusZ_ClusPhi_layer2 = GetHistogram(histfname, 'hM_ClusZ_ClusPhi_layer2')
    hM_ClusZ_ClusPhi_layer3 = GetHistogram(histfname, 'hM_ClusZ_ClusPhi_layer3')
    hM_ClusEta_ClusZSize_all = GetHistogram(histfname, 'hM_ClusEta_ClusZSize_all')
    hM_ClusEta_ClusZSize_layer1 = GetHistogram(histfname, 'hM_ClusEta_ClusZSize_layer1')
    hM_ClusEta_ClusZSize_layer2 = GetHistogram(histfname, 'hM_ClusEta_ClusZSize_layer2')
    hM_ClusEta_ClusZSize_layer3 = GetHistogram(histfname, 'hM_ClusEta_ClusZSize_layer3')
    hM_ClusPhi_ClusPhiSize_all = GetHistogram(histfname, 'hM_ClusPhi_ClusPhiSize_all')
    hM_ClusPhi_ClusPhiSize_layer1 = GetHistogram(histfname, 'hM_ClusPhi_ClusPhiSize_layer1')
    hM_ClusPhi_ClusPhiSize_layer2 = GetHistogram(histfname, 'hM_ClusPhi_ClusPhiSize_layer2')
    hM_ClusPhi_ClusPhiSize_layer3 = GetHistogram(histfname, 'hM_ClusPhi_ClusPhiSize_layer3')
    hM_ClusEta_ClusADC_all = GetHistogram(histfname, 'hM_ClusEta_ClusADC_all')
    hM_ClusEta_ClusADC_layer1 = GetHistogram(histfname, 'hM_ClusEta_ClusADC_layer1')
    hM_ClusEta_ClusADC_layer2 = GetHistogram(histfname, 'hM_ClusEta_ClusADC_layer2')
    hM_ClusEta_ClusADC_layer3 = GetHistogram(histfname, 'hM_ClusEta_ClusADC_layer3')
    hM_ClusZSize_ClusPhiSize_all = GetHistogram(histfname, 'hM_ClusZSize_ClusPhiSize_all')
    hM_ClusZSize_ClusPhiSize_layer1 = GetHistogram(histfname, 'hM_ClusZSize_ClusPhiSize_layer1')
    hM_ClusZSize_ClusPhiSize_layer2 = GetHistogram(histfname, 'hM_ClusZSize_ClusPhiSize_layer2')
    hM_ClusZSize_ClusPhiSize_layer3 = GetHistogram(histfname, 'hM_ClusZSize_ClusPhiSize_layer3')
    hM_ClusZSize_ClusADC_all = GetHistogram(histfname, 'hM_ClusZSize_ClusADC_all')
    hM_ClusZSize_ClusADC_layer1 = GetHistogram(histfname, 'hM_ClusZSize_ClusADC_layer1')
    hM_ClusZSize_ClusADC_layer2 = GetHistogram(histfname, 'hM_ClusZSize_ClusADC_layer2')
    hM_ClusZSize_ClusADC_layer3 = GetHistogram(histfname, 'hM_ClusZSize_ClusADC_layer3')
    hM_ClusPhiSize_ClusADC_all = GetHistogram(histfname, 'hM_ClusPhiSize_ClusADC_all')
    hM_ClusPhiSize_ClusADC_layer1 = GetHistogram(histfname, 'hM_ClusPhiSize_ClusADC_layer1')
    hM_ClusPhiSize_ClusADC_layer2 = GetHistogram(histfname, 'hM_ClusPhiSize_ClusADC_layer2')
    hM_ClusPhiSize_ClusADC_layer3 = GetHistogram(histfname, 'hM_ClusPhiSize_ClusADC_layer3')

    # Draw_1Dhist(hist, norm1, logy, ymaxscale, XaxisName, Ytitle_unit, outname):
    Draw_1Dhist(hM_ClusZ_all, False, False, 1.3, 'Cluster Z pos (cm)', 'cm', plotpath+'ClusZ_all')
    Draw_1Dhist(hM_ClusZ_layer1, False, False, 1.3, 'Cluster Z pos (cm)', 'cm', plotpath+'ClusZ_layer1')
    Draw_1Dhist(hM_ClusZ_layer2, False, False, 1.3, 'Cluster Z pos (cm)', 'cm', plotpath+'ClusZ_layer2')
    Draw_1Dhist(hM_ClusZ_layer3, False, False, 1.3, 'Cluster Z pos (cm)', 'cm', plotpath+'ClusZ_layer3')
    Draw_1Dhist(hM_ClusEtaPV_all, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', plotpath+'ClusEtaPV_all')
    Draw_1Dhist(hM_ClusEtaPV_layer1, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', plotpath+'ClusEtaPV_layer1')
    Draw_1Dhist(hM_ClusEtaPV_layer2, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', plotpath+'ClusEtaPV_layer2')
    Draw_1Dhist(hM_ClusEtaPV_layer3, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', plotpath+'ClusEtaPV_layer3')
    Draw_1Dhist(hM_ClusEtaOri_all, False, False, 1.3, 'Cluster #eta', '', plotpath+'ClusEtaOri_all')
    Draw_1Dhist(hM_ClusEtaOri_layer1, False, False, 1.3, 'Cluster #eta', '', plotpath+'ClusEtaOri_layer1')
    Draw_1Dhist(hM_ClusEtaOri_layer2, False, False, 1.3, 'Cluster #eta', '', plotpath+'ClusEtaOri_layer2')
    Draw_1Dhist(hM_ClusEtaOri_layer3, False, False, 1.3, 'Cluster #eta', '', plotpath+'ClusEtaOri_layer3')
    Draw_1Dhist(hM_ClusPhi_all, False, False, 1.3, 'Cluster #phi', '', plotpath+'ClusPhi_all')
    Draw_1Dhist(hM_ClusPhi_layer1, False, False, 1.3, 'Cluster #phi', '', plotpath+'ClusPhi_layer1')
    Draw_1Dhist(hM_ClusPhi_layer2, False, False, 1.3, 'Cluster #phi', '', plotpath+'ClusPhi_layer2')
    Draw_1Dhist(hM_ClusPhi_layer3, False, False, 1.3, 'Cluster #phi', '', plotpath+'ClusPhi_layer3')
    Draw_1Dhist(hM_ClusADC_all, False, True, 100, 'Cluster ADC', '', plotpath+'ClusADC_all')
    Draw_1Dhist(hM_ClusADC_layer1, False, True, 100, 'Cluster ADC', '', plotpath+'ClusADC_layer1')
    Draw_1Dhist(hM_ClusADC_layer2, False, True, 100, 'Cluster ADC', '', plotpath+'ClusADC_layer2')
    Draw_1Dhist(hM_ClusADC_layer3, False, True, 100, 'Cluster ADC', '', plotpath+'ClusADC_layer3')
    Draw_1Dhist(hM_ClusZSize_all, False, True, 100, 'Cluster Z size', '', plotpath+'ClusZSize_all')
    Draw_1Dhist(hM_ClusZSize_layer1, False, True, 100, 'Cluster Z size', '', plotpath+'ClusZSize_layer1')
    Draw_1Dhist(hM_ClusZSize_layer2, False, True, 100, 'Cluster Z size', '', plotpath+'ClusZSize_layer2')
    Draw_1Dhist(hM_ClusZSize_layer3, False, True, 100, 'Cluster Z size', '', plotpath+'ClusZSize_layer3')
    Draw_1Dhist(hM_ClusPhiSize_all, False, True, 100, 'Cluster #phi size', '', plotpath+'ClusPhiSize_all')
    Draw_1Dhist(hM_ClusPhiSize_layer1, False, True, 100, 'Cluster #phi size', '', plotpath+'ClusPhiSize_layer1')
    Draw_1Dhist(hM_ClusPhiSize_layer2, False, True, 100, 'Cluster #phi size', '', plotpath+'ClusPhiSize_layer2')
    Draw_1Dhist(hM_ClusPhiSize_layer3, False, True, 100, 'Cluster #phi size', '', plotpath+'ClusPhiSize_layer3')
    Draw_1Dhist(hM_ClusPairDr_layer1, False, False, 1.3, 'Cluster-cluster #DeltaR', '', plotpath+'ClusPairDr_layer1')
    Draw_1Dhist(hM_ClusPairDr_layer2, False, False, 1.3, 'Cluster-cluster #DeltaR', '', plotpath+'ClusPairDr_layer2')
    Draw_1Dhist(hM_ClusPairDr_layer3, False, False, 1.3, 'Cluster-cluster #DeltaR', '', plotpath+'ClusPairDr_layer3')
    # Draw_2Dhist(hist, logz, norm1, rmargin, XaxisName, YaxisName, drawopt, outname):
    Draw_2Dhist(hM_ClusX_ClusY_all, False, False, 0.15, 'Cluster X pos (cm)', 'Cluster Y pos (cm)', 'colz', plotpath+'ClusX_ClusY_all')
    Draw_2Dhist(hM_ClusZ_ClusPhi_all, False, False, 0.16, 'Cluster Z pos (cm)', 'Cluster #phi', 'colz', plotpath+'ClusZ_ClusPhi_all')
    Draw_2Dhist(hM_ClusZ_ClusPhi_layer1, False, False, 0.16, 'Cluster Z pos (cm)', 'Cluster #phi', 'colz', plotpath+'ClusZ_ClusPhi_layer1')
    Draw_2Dhist(hM_ClusZ_ClusPhi_layer2, False, False, 0.16, 'Cluster Z pos (cm)', 'Cluster #phi', 'colz', plotpath+'ClusZ_ClusPhi_layer2')
    Draw_2Dhist(hM_ClusZ_ClusPhi_layer3, False, False, 0.16, 'Cluster Z pos (cm)', 'Cluster #phi', 'colz', plotpath+'ClusZ_ClusPhi_layer3')
    Draw_2Dhist(hM_ClusEta_ClusZSize_all, True, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster Z size', 'colz', plotpath+'ClusEta_ClusZSize_all')
    Draw_2Dhist(hM_ClusEta_ClusZSize_layer1, True, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster Z size', 'colz', plotpath+'ClusEta_ClusZSize_layer1')
    Draw_2Dhist(hM_ClusEta_ClusZSize_layer2, True, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster Z size', 'colz', plotpath+'ClusEta_ClusZSize_layer2')
    Draw_2Dhist(hM_ClusEta_ClusZSize_layer3, True, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster Z size', 'colz', plotpath+'ClusEta_ClusZSize_layer3')
    Draw_2Dhist(hM_ClusPhi_ClusPhiSize_all, False, False, 0.16, 'Cluster #phi', 'Cluster #phi size', 'colz', plotpath+'ClusPhi_ClusPhiSize_all')
    Draw_2Dhist(hM_ClusPhi_ClusPhiSize_layer1, False, False, 0.16, 'Cluster #phi', 'Cluster #phi size', 'colz', plotpath+'ClusPhi_ClusPhiSize_layer1')
    Draw_2Dhist(hM_ClusPhi_ClusPhiSize_layer2, False, False, 0.16, 'Cluster #phi', 'Cluster #phi size', 'colz', plotpath+'ClusPhi_ClusPhiSize_layer2')
    Draw_2Dhist(hM_ClusPhi_ClusPhiSize_layer3, False, False, 0.16, 'Cluster #phi', 'Cluster #phi size', 'colz', plotpath+'ClusPhi_ClusPhiSize_layer3')
    Draw_2Dhist(hM_ClusEta_ClusADC_all, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC', 'colz', plotpath+'ClusEta_ClusADC_all')
    Draw_2Dhist(hM_ClusEta_ClusADC_layer1, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC', 'colz', plotpath+'ClusEta_ClusADC_layer1')
    Draw_2Dhist(hM_ClusEta_ClusADC_layer2, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC', 'colz', plotpath+'ClusEta_ClusADC_layer2')
    Draw_2Dhist(hM_ClusEta_ClusADC_layer3, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC', 'colz', plotpath+'ClusEta_ClusADC_layer3')    
    Draw_2Dhist(hM_ClusZSize_ClusPhiSize_all, True, False, 0.16, 'Cluster Z size', 'Cluster #phi size', 'colz', plotpath+'ClusZSize_ClusPhiSize_all')
    Draw_2Dhist(hM_ClusZSize_ClusPhiSize_layer1, True, False, 0.16, 'Cluster Z size', 'Cluster #phi size', 'colz', plotpath+'ClusZSize_ClusPhiSize_layer1')
    Draw_2Dhist(hM_ClusZSize_ClusPhiSize_layer2, True, False, 0.16, 'Cluster Z size', 'Cluster #phi size', 'colz', plotpath+'ClusZSize_ClusPhiSize_layer2')
    Draw_2Dhist(hM_ClusZSize_ClusPhiSize_layer3, True, False, 0.16, 'Cluster Z size', 'Cluster #phi size' , 'colz', plotpath+'ClusZSize_ClusPhiSize_layer3')   
    Draw_2Dhist(hM_ClusZSize_ClusADC_all, True, False, 0.16, 'Cluster Z size', 'Cluster #phi size', 'colz', plotpath+'ClusZSize_ClusADC_all')
    Draw_2Dhist(hM_ClusZSize_ClusADC_layer1, True, False, 0.16, 'Cluster Z size', 'Cluster ADC', 'colz', plotpath+'ClusZSize_ClusADC_layer1')
    Draw_2Dhist(hM_ClusZSize_ClusADC_layer2, True, False, 0.16, 'Cluster Z size', 'Cluster ADC', 'colz', plotpath+'ClusZSize_ClusADC_layer2')
    Draw_2Dhist(hM_ClusZSize_ClusADC_layer3, True, False, 0.16, 'Cluster Z size', 'Cluster ADC' , 'colz', plotpath+'ClusZSize_ClusADC_layer3')   
    Draw_2Dhist(hM_ClusPhiSize_ClusADC_all, True, False, 0.16, 'Cluster #phi size', 'Cluster ADC', 'colz', plotpath+'ClusPhiSize_ClusADC_all')
    Draw_2Dhist(hM_ClusPhiSize_ClusADC_layer1, True, False, 0.16, 'Cluster #phi size', 'Cluster ADC', 'colz', plotpath+'ClusPhiSize_ClusADC_layer1')
    Draw_2Dhist(hM_ClusPhiSize_ClusADC_layer2, True, False, 0.16, 'Cluster #phi size', 'Cluster ADC', 'colz', plotpath+'ClusPhiSize_ClusADC_layer2')
    Draw_2Dhist(hM_ClusPhiSize_ClusADC_layer3, True, False, 0.16, 'Cluster #phi size', 'Cluster ADC' , 'colz', plotpath+'ClusPhiSize_ClusADC_layer3')   