#! /usr/bin/env python
from optparse import OptionParser
import sys
import os
import datetime
from array import *
from ROOT import *
import numpy
import math
import glob
from plotUtil import *

gROOT.LoadMacro('./sPHENIXStyle/sPhenixStyle.C')
gROOT.ProcessLine('SetsPhenixStyle()')
gROOT.SetBatch(True)
# gStyle.SetPalette(kSunset)
# TColor.InvertPalette()

def main(misalignnum):
    plotpath = './TrackletAna/TrackletAna_MisAlignNum{}/'.format(misalignnum)
    # vtxZmean = -3
    # vtxZwidth = 8
    # plotpath = './TrackletAna_Simple1000Pions_VtxZmean{}cm_VtxZwidth{}cm/'.format(vtxZmean, vtxZwidth)
    os.makedirs(plotpath, exist_ok=True)

    hM_ClusX_all = GetHist('hM_ClusX_all', misalignnum)
    hM_ClusY_all = GetHist('hM_ClusY_all', misalignnum)
    hM_ClusZ_all = GetHist('hM_ClusZ_all', misalignnum)
    hM_ClusEta_all = GetHist('hM_ClusEta_all', misalignnum)
    hM_ClusPhi_all = GetHist('hM_ClusPhi_all', misalignnum)
    hM_ClusX_ClusY_all = GetHist('hM_ClusX_ClusY_all', misalignnum)
    hM_ClusZ_ClusPhi_all = GetHist('hM_ClusZ_ClusPhi_all', misalignnum)
    hM_ClusZ_TruthPVz_all = GetHist('hM_ClusZ_TruthPVz_all', misalignnum)
    hM_ClusPhi_TruthPVz_all = GetHist('hM_ClusPhi_TruthPVz_all', misalignnum)
    hM_ClusX_layer1 = GetHist('hM_ClusX_layer1', misalignnum)
    hM_ClusY_layer1 = GetHist('hM_ClusY_layer1', misalignnum)
    hM_ClusZ_layer1 = GetHist('hM_ClusZ_layer1', misalignnum)
    hM_ClusEta_layer1 = GetHist('hM_ClusEta_layer1', misalignnum)
    hM_ClusPhi_layer1 = GetHist('hM_ClusPhi_layer1', misalignnum)
    hM_ClusZ_ClusPhi_layer1 = GetHist('hM_ClusZ_ClusPhi_layer1', misalignnum)
    hM_ClusZ_TruthPVz_layer1 = GetHist('hM_ClusZ_TruthPVz_layer1', misalignnum)
    hM_ClusPhi_TruthPVz_layer1 = GetHist('hM_ClusPhi_TruthPVz_layer1', misalignnum)
    hM_ClusX_layer2 = GetHist('hM_ClusX_layer2', misalignnum)
    hM_ClusY_layer2 = GetHist('hM_ClusY_layer2', misalignnum)
    hM_ClusZ_layer2 = GetHist('hM_ClusZ_layer2', misalignnum)
    hM_ClusEta_layer2 = GetHist('hM_ClusEta_layer2', misalignnum)
    hM_ClusPhi_layer2 = GetHist('hM_ClusPhi_layer2', misalignnum)
    hM_ClusZ_ClusPhi_layer2 = GetHist('hM_ClusZ_ClusPhi_layer2', misalignnum)
    hM_ClusZ_TruthPVz_layer2 = GetHist('hM_ClusZ_TruthPVz_layer2', misalignnum)
    hM_ClusPhi_TruthPVz_layer2 = GetHist('hM_ClusPhi_TruthPVz_layer2', misalignnum)
    hM_ClusX_layer3 = GetHist('hM_ClusX_layer3', misalignnum)
    hM_ClusY_layer3 = GetHist('hM_ClusY_layer3', misalignnum)
    hM_ClusZ_layer3 = GetHist('hM_ClusZ_layer3', misalignnum)
    hM_ClusEta_layer3 = GetHist('hM_ClusEta_layer3', misalignnum)
    hM_ClusPhi_layer3 = GetHist('hM_ClusPhi_layer3', misalignnum)
    hM_ClusZ_ClusPhi_layer3 = GetHist('hM_ClusZ_ClusPhi_layer3', misalignnum)
    hM_ClusZ_TruthPVz_layer3 = GetHist('hM_ClusZ_TruthPVz_layer3', misalignnum)
    hM_ClusPhi_TruthPVz_layer3 = GetHist('hM_ClusPhi_TruthPVz_layer3', misalignnum)

    hM_dPhi_dEta_woCuts = GetHist('hM_dPhi_dEta_woCuts', misalignnum)
    hM_dEta_proto = GetHist('hM_dEta_proto', misalignnum)
    hM_dEta_proto_altrange = GetHist('hM_dEta_proto_altrange', misalignnum)
    hM_dEta_proto_altrange2 = GetHist('hM_dEta_proto_altrange2', misalignnum)
    hM_dPhi_proto = GetHist('hM_dPhi_proto', misalignnum)
    hM_dPhi_proto_altrange = GetHist('hM_dPhi_proto_altrange', misalignnum)
    hM_Eta_proto = GetHist('hM_Eta_proto', misalignnum)
    hM_Eta_proto_PVzRange1 = GetHist('hM_Eta_proto_PVzRange1', misalignnum)
    hM_Eta_proto_PVzRange2 = GetHist('hM_Eta_proto_PVzRange2', misalignnum)
    hM_Eta_proto_PVzRange3 = GetHist('hM_Eta_proto_PVzRange3', misalignnum)
    hM_Eta_proto_PVzRange4 = GetHist('hM_Eta_proto_PVzRange4', misalignnum)
    hM_Eta_proto_PVzRange5 = GetHist('hM_Eta_proto_PVzRange5', misalignnum)
    hM_Phi_proto = GetHist('hM_Phi_proto', misalignnum)
    hM_dR_proto = GetHist('hM_dR_proto', misalignnum)
    hM_dR_proto_altrange = GetHist('hM_dR_proto_altrange', misalignnum)
    hM_dR_proto_LogX = GetHist('hM_dR_proto_LogX', misalignnum)
    hM_Eta_hit1_proto = GetHist('hM_Eta_hit1_proto', misalignnum)
    hM_Phi_hit1_proto = GetHist('hM_Phi_hit1_proto', misalignnum)
    hM_Eta_hit2_proto = GetHist('hM_Eta_hit2_proto', misalignnum)
    hM_Phi_hit2_proto = GetHist('hM_Phi_hit2_proto', misalignnum)
    hM_Eta_vtxZ_proto = GetHist('hM_Eta_vtxZ_proto', misalignnum)
    hM_hit1Eta_hit2Eta_proto = GetHist('hM_hit1Eta_hit2Eta_proto', misalignnum)
    hM_hit1Phi_hit2Phi_proto = GetHist('hM_hit1Phi_hit2Phi_proto', misalignnum)
    hM_dPhi_dEta_proto = GetHist('hM_dPhi_dEta_proto', misalignnum)
    hM_dPhi_dEta_proto_altrange = GetHist('hM_dPhi_dEta_proto_altrange', misalignnum)
    hM_dEta_reco = GetHist('hM_dEta_reco', misalignnum)
    hM_dEta_reco_altrange = GetHist('hM_dEta_reco_altrange', misalignnum)
    hM_dEta_reco_altrange2 = GetHist('hM_dEta_reco_altrange2', misalignnum)
    hM_dPhi_reco = GetHist('hM_dPhi_reco', misalignnum)
    hM_dPhi_reco_norm1_logy = GetHist('hM_dPhi_reco', misalignnum)
    for h in hM_dPhi_reco_norm1_logy:
        h.SetName('hM_dPhi_reco_norm1_logy')
    hM_dPhi_reco_altrange = GetHist('hM_dPhi_reco_altrange', misalignnum)
    hM_Eta_reco = GetHist('hM_Eta_reco', misalignnum)
    hM_Phi_reco = GetHist('hM_Phi_reco', misalignnum)
    hM_dR_reco = GetHist('hM_dR_reco', misalignnum)
    hM_dR_reco_altrange = GetHist('hM_dR_reco_altrange', misalignnum)
    hM_dR_reco_LogX = GetHist('hM_dR_reco_LogX', misalignnum)
    hM_Eta_hit1_reco = GetHist('hM_Eta_hit1_reco', misalignnum)
    hM_Phi_hit1_reco = GetHist('hM_Phi_hit1_reco', misalignnum)
    hM_Eta_hit2_reco = GetHist('hM_Eta_hit2_reco', misalignnum)
    hM_Phi_hit2_reco = GetHist('hM_Phi_hit2_reco', misalignnum)
    hM_Eta_vtxZ_reco = GetHist('hM_Eta_vtxZ_reco', misalignnum)
    hM_hit1Eta_hit2Eta_reco = GetHist('hM_hit1Eta_hit2Eta_reco', misalignnum)
    hM_hit1Phi_hit2Phi_reco = GetHist('hM_hit1Phi_hit2Phi_reco', misalignnum)
    hM_Eta_vtxZ_reco = GetHist('hM_Eta_vtxZ_reco', misalignnum)
    hM_dPhi_dEta_reco = GetHist('hM_dPhi_dEta_reco', misalignnum)
    hM_dPhi_dEta_reco_altrange = GetHist('hM_dPhi_dEta_reco_altrange', misalignnum)
    hM_PVz = GetHist('hM_PVz', misalignnum)

    # hM_dPhi_dEta_woCuts = GetHist_Single('hM_dPhi_dEta_woCuts')
    # hM_dEta_proto = GetHist_Single('hM_dEta_proto')
    # hM_dPhi_proto = GetHist_Single('hM_dPhi_proto')
    # hM_Eta_proto = GetHist_Single('hM_Eta_proto')
    # hM_Phi_proto = GetHist_Single('hM_Phi_proto')
    # hM_dR_proto = GetHist_Single('hM_dR_proto')
    # hM_Eta_hit1_proto = GetHist_Single('hM_Eta_hit1_proto')
    # hM_Phi_hit1_proto = GetHist_Single('hM_Phi_hit1_proto')
    # hM_Eta_hit2_proto = GetHist_Single('hM_Eta_hit2_proto')
    # hM_Phi_hit2_proto = GetHist_Single('hM_Phi_hit2_proto')
    # hM_Eta_vtxZ_proto = GetHist_Single('hM_Eta_vtxZ_proto')
    # hM_hit1Eta_hit2Eta_proto = GetHist_Single('hM_hit1Eta_hit2Eta_proto')
    # hM_hit1Phi_hit2Phi_proto = GetHist_Single('hM_hit1Phi_hit2Phi_proto')
    # hM_dPhi_dEta_proto = GetHist_Single('hM_dPhi_dEta_proto')
    # hM_dEta_reco = GetHist_Single('hM_dEta_reco')
    # hM_dPhi_reco = GetHist_Single('hM_dPhi_reco')
    # hM_Eta_reco = GetHist_Single('hM_Eta_reco')
    # hM_Phi_reco = GetHist_Single('hM_Phi_reco')
    # hM_dR_reco = GetHist_Single('hM_dR_reco')
    # hM_Eta_hit1_reco = GetHist_Single('hM_Eta_hit1_reco')
    # hM_Phi_hit1_reco = GetHist_Single('hM_Phi_hit1_reco')
    # hM_Eta_hit2_reco = GetHist_Single('hM_Eta_hit2_reco')
    # hM_Phi_hit2_reco = GetHist_Single('hM_Phi_hit2_reco')
    # hM_Eta_vtxZ_reco = GetHist_Single('hM_Eta_vtxZ_reco')
    # hM_hit1Eta_hit2Eta_reco = GetHist_Single('hM_hit1Eta_hit2Eta_reco')
    # hM_hit1Phi_hit2Phi_reco = GetHist_Single('hM_hit1Phi_hit2Phi_reco')
    # hM_Eta_vtxZ_reco = GetHist_Single('hM_Eta_vtxZ_reco')
    # hM_dPhi_dEta_reco = GetHist_Single('hM_dPhi_dEta_reco')
    # hM_PVz = GetHist_Single('hM_PVz')

    Draw_1Dhist(hM_PVz[0], False, False, 1.3, 'Primary vertex V_{z} (cm)', 'cm', plotpath+'PVz')

    Draw_1Dhist(hM_ClusX_all[0], False, False, 1.3, 'Cluster X pos (cm)', 'cm', plotpath+'RecoClusters_ClusX_all')
    Draw_1Dhist(hM_ClusY_all[0], False, False, 1.3, 'Cluster Y pos (cm)', 'cm', plotpath+'RecoClusters_ClusY_all')
    Draw_1Dhist(hM_ClusZ_all[0], False, False, 1.3, 'Cluster Z pos (cm)', 'cm', plotpath+'RecoClusters_ClusZ_all')
    Draw_1Dhist(hM_ClusEta_all[0], False, False, 1.3, 'Cluster #eta', '', plotpath+'RecoClusters_ClusEta_all')
    Draw_1Dhist(hM_ClusPhi_all[0], False, False, 1.3, 'Cluster #phi', '', plotpath+'RecoClusters_ClusPhi_all')
    Draw_1Dhist(hM_ClusX_layer1[0], False, False, 1.3, 'Cluster X pos (cm)', 'cm', plotpath+'RecoClusters_ClusX_layer1')
    Draw_1Dhist(hM_ClusY_layer1[0], False, False, 1.3, 'Cluster Y pos (cm)', 'cm', plotpath+'RecoClusters_ClusY_layer1')
    Draw_1Dhist(hM_ClusZ_layer1[0], False, False, 1.3, 'Cluster Z pos (cm)', 'cm', plotpath+'RecoClusters_ClusZ_layer1')
    Draw_1Dhist(hM_ClusEta_layer1[0], False, False, 1.3, 'Cluster #eta', '', plotpath+'RecoClusters_ClusEta_layer1')
    Draw_1Dhist(hM_ClusPhi_layer1[0], False, False, 1.3, 'Cluster #phi', '', plotpath+'RecoClusters_ClusPhi_layer1')
    Draw_1Dhist(hM_ClusX_layer2[0], False, False, 1.3, 'Cluster X pos (cm)', 'cm', plotpath+'RecoClusters_ClusX_layer2')
    Draw_1Dhist(hM_ClusY_layer2[0], False, False, 1.3, 'Cluster Y pos (cm)', 'cm', plotpath+'RecoClusters_ClusY_layer2')
    Draw_1Dhist(hM_ClusZ_layer2[0], False, False, 1.3, 'Cluster Z pos (cm)', 'cm', plotpath+'RecoClusters_ClusZ_layer2')
    Draw_1Dhist(hM_ClusEta_layer2[0], False, False, 1.3, 'Cluster #eta', '', plotpath+'RecoClusters_ClusEta_layer2')
    Draw_1Dhist(hM_ClusPhi_layer2[0], False, False, 1.3, 'Cluster #phi', '', plotpath+'RecoClusters_ClusPhi_layer2')
    Draw_1Dhist(hM_ClusX_layer3[0], False, False, 1.3, 'Cluster X pos (cm)', 'cm', plotpath+'RecoClusters_ClusX_layer3')
    Draw_1Dhist(hM_ClusY_layer3[0], False, False, 1.3, 'Cluster Y pos (cm)', 'cm', plotpath+'RecoClusters_ClusY_layer3')
    Draw_1Dhist(hM_ClusZ_layer3[0], False, False, 1.3, 'Cluster Z pos (cm)', 'cm', plotpath+'RecoClusters_ClusZ_layer3')
    Draw_1Dhist(hM_ClusEta_layer3[0], False, False, 1.3, 'Cluster #eta', '', plotpath+'RecoClusters_ClusEta_layer3')
    Draw_1Dhist(hM_ClusPhi_layer3[0], False, False, 1.3, 'Cluster #phi', '', plotpath+'RecoClusters_ClusPhi_layer3')
    
    Draw_1Dhist(hM_dPhi_reco_norm1_logy[0], True, True, 100, 'Reco-tracklet #Delta#phi', '', plotpath+'RecoTracklet_dPhi_layer12_norm1_logy')

    Draw_1DhistsComp(hM_Eta_hit1_proto, False, False, False, 1.5, 'Proto-tracklet #eta_{1}', '', plotpath+'ProtoTracklet_Eta1_comp')
    Draw_1DhistsComp(hM_dEta_proto, False, False, False, 1.3, 'Proto-tracklet #Delta#eta', '', plotpath+'ProtoTracklet_dEta_comp')
    hM_dEta_proto_altrange[0].GetXaxis().SetMaxDigits(2)
    Draw_1DhistsComp(hM_dEta_proto_altrange, False, False, False, 1.3, 'Proto-tracklet #Delta#eta', '', plotpath+'ProtoTracklet_dEta_altrange_comp')
    hM_dEta_proto_altrange2[0].GetXaxis().SetMaxDigits(2)
    Draw_1DhistsComp(hM_dEta_proto_altrange2, False, False, False, 1.8, 'Proto-tracklet #Delta#eta', '', plotpath+'ProtoTracklet_dEta_altrange2_comp')
    Draw_1DhistsComp(hM_dPhi_proto, False, False, False, 1.3, 'Proto-tracklet #Delta#phi', '', plotpath+'ProtoTracklet_dPhi_comp')
    Draw_1DhistsComp(hM_dPhi_proto_altrange, False, False, False, 1.3, 'Proto-tracklet #Delta#phi', '', plotpath+'ProtoTracklet_dPhi_altrange_comp')
    Draw_1DhistsComp(hM_Eta_proto, False, False, False, 1.5, 'Proto-tracklet #eta', '', plotpath+'ProtoTracklet_Eta_comp')
    Draw_1DhistsComp(hM_Eta_proto_PVzRange1, False, False, False, 1.5, 'Proto-tracklet #eta', '', plotpath+'ProtoTracklet_Eta_PVzRange1_comp')
    Draw_1DhistsComp(hM_Eta_proto_PVzRange2, False, False, False, 1.5, 'Proto-tracklet #eta', '', plotpath+'ProtoTracklet_Eta_PVzRange2_comp')
    Draw_1DhistsComp(hM_Eta_proto_PVzRange3, False, False, False, 1.5, 'Proto-tracklet #eta', '', plotpath+'ProtoTracklet_Eta_PVzRange3_comp')
    Draw_1DhistsComp(hM_Eta_proto_PVzRange4, False, False, False, 1.5, 'Proto-tracklet #eta', '', plotpath+'ProtoTracklet_Eta_PVzRange4_comp')
    Draw_1DhistsComp(hM_Eta_proto_PVzRange5, False, False, False, 1.5, 'Proto-tracklet #eta', '', plotpath+'ProtoTracklet_Eta_PVzRange5_comp')
    Draw_1DhistsComp(hM_Phi_proto, False, False, False, 1.5, 'Proto-tracklet #phi', '', plotpath+'ProtoTracklet_Phi_comp')
    Draw_1DhistsComp(hM_dR_proto, False, False, True, 1.3, 'Proto-tracklet #DeltaR', '', plotpath+'ProtoTracklet_dR_comp')
    Draw_1DhistsComp(hM_dR_proto_altrange, False, False, True, 1.3, 'Proto-tracklet #DeltaR', '', plotpath+'ProtoTracklet_dR_altrange_comp')
    Draw_1DhistsComp(hM_dR_proto_LogX, False, True, True, 1.3, 'Proto-tracklet #DeltaR', '', plotpath+'ProtoTracklet_dR_logX_comp')
    Draw_1DhistsComp(hM_dEta_reco, False, False, True, 1.3, 'Reco-tracklet #Delta#eta', '', plotpath+'RecoTracklet_dEta_comp')
    hM_dEta_reco_altrange[0].GetXaxis().SetMaxDigits(2)
    Draw_1DhistsComp(hM_dEta_reco_altrange, False, False, False, 1.3, 'Reco-tracklet #Delta#eta', '', plotpath+'RecoTracklet_dEta_altrange_comp')
    hM_dEta_reco_altrange2[0].GetXaxis().SetMaxDigits(2)
    Draw_1DhistsComp(hM_dEta_reco_altrange2, False, False, False, 1.3, 'Reco-tracklet #Delta#eta', '', plotpath+'RecoTracklet_dEta_altrange2_comp')
    Draw_1DhistsComp(hM_dPhi_reco, False, False, False, 1.3, 'Reco-tracklet #Delta#phi', '', plotpath+'RecoTracklet_dPhi_comp')
    Draw_1DhistsComp(hM_dPhi_reco_norm1_logy, True, False, True, 1.3, 'Reco-tracklet #Delta#phi', '', plotpath+'RecoTracklet_dPhi_comp_norm1_logy')
    Draw_1DhistsComp(hM_dPhi_reco_altrange, False, False, False, 1.3, 'Reco-tracklet #Delta#phi', '', plotpath+'RecoTracklet_dPhi_altrange_comp')
    Draw_1DhistsComp(hM_Eta_reco, False, False, False, 1.5, 'Reco-tracklet #eta', '', plotpath+'RecoTracklet_Eta_comp')
    Draw_1DhistsComp(hM_Phi_reco, False, False, False, 1.5, 'Reco-tracklet #phi', '', plotpath+'RecoTracklet_Phi_comp')
    Draw_1DhistsComp(hM_dR_reco, False, False, True, 1.3, 'Reco-tracklet #DeltaR', '', plotpath+'RecoTracklet_dR_comp')
    Draw_1DhistsComp(hM_dR_reco_altrange, False, False, True, 1.3, 'Reco-tracklet #DeltaR', '', plotpath+'RecoTracklet_dR_altrange_comp')
    Draw_1DhistsComp(hM_dR_reco_LogX, False, True, True, 1.3, 'Reco-tracklet #DeltaR', '', plotpath+'RecoTracklet_dR_logX_comp')

    Draw_2Dhist(hM_ClusX_ClusY_all[0], False, False, 0.15, 'Cluster X pos (cm)', 'Cluster Y pos (cm)', plotpath+'RecoClusters_ClusXClusY_all')
    Draw_2Dhist(hM_ClusX_ClusY_all[0], False, False, 0.16, 'Cluster X pos (cm)', 'Cluster Y pos (cm)', plotpath+'RecoClusters_ClusXClusY_all')
    Draw_2Dhist(hM_ClusZ_ClusPhi_all[0], False, False, 0.16, 'Cluster Z pos (cm)', 'Cluster #phi', plotpath+'RecoClusters_ClusZClusPhi_all')
    Draw_2Dhist(hM_ClusZ_ClusPhi_layer1[0], False, False, 0.16, 'Cluster Z pos (cm)', 'Cluster #phi', plotpath+'RecoClusters_ClusZClusPhi_layer1')
    Draw_2Dhist(hM_ClusZ_ClusPhi_layer2[0], False, False, 0.16, 'Cluster Z pos (cm)', 'Cluster #phi', plotpath+'RecoClusters_ClusZClusPhi_layer2')
    Draw_2Dhist(hM_ClusZ_ClusPhi_layer3[0], False, False, 0.16, 'Cluster Z pos (cm)', 'Cluster #phi', plotpath+'RecoClusters_ClusZClusPhi_layer3')
    Draw_2Dhist(hM_ClusZ_TruthPVz_all[0], False, False, 0.16, 'Cluster Z pos (cm)', 'Truth PV Z pos (cm)', plotpath+'RecoClusters_ClusZTruthPVz_all') 
    Draw_2Dhist(hM_ClusZ_TruthPVz_layer1[0], False, False, 0.16, 'Cluster Z pos (cm)', 'Truth PV Z pos (cm)', plotpath+'RecoClusters_ClusZTruthPVz_layer1') 
    Draw_2Dhist(hM_ClusZ_TruthPVz_layer2[0], False, False, 0.16, 'Cluster Z pos (cm)', 'Truth PV Z pos (cm)', plotpath+'RecoClusters_ClusZTruthPVz_layer2') 
    Draw_2Dhist(hM_ClusZ_TruthPVz_layer3[0], False, False, 0.16, 'Cluster Z pos (cm)', 'Truth PV Z pos (cm)', plotpath+'RecoClusters_ClusZTruthPVz_layer3')
    Draw_2Dhist(hM_ClusPhi_TruthPVz_all[0], False, False, 0.16, 'Cluster #phi', 'Truth PV Z pos (cm)', plotpath+'RecoClusters_ClusPhiTruthPVz_all') 
    Draw_2Dhist(hM_ClusPhi_TruthPVz_layer1[0], False, False, 0.16, 'Cluster #phi', 'Truth PV Z pos (cm)', plotpath+'RecoClusters_ClusPhiTruthPVz_layer1') 
    Draw_2Dhist(hM_ClusPhi_TruthPVz_layer2[0], False, False, 0.16, 'Cluster #phi', 'Truth PV Z pos (cm)', plotpath+'RecoClusters_ClusPhiTruthPVz_layer2') 
    Draw_2Dhist(hM_ClusPhi_TruthPVz_layer3[0], False, False, 0.16, 'Cluster #phi', 'Truth PV Z pos (cm)', plotpath+'RecoClusters_ClusPhiTruthPVz_layer3')

    Draw_2Dhist(hM_dPhi_dEta_woCuts[0], True, False, 0.13, '#Delta#phi', '#Delta#eta', plotpath+'dPhi_dEta_woCuts_layer12')
    Draw_2Dhist(hM_Eta_vtxZ_proto[0], False, False, 0.16, 'Proto-tracklet #eta', 'Primary vertex V_{z} (cm)', plotpath+'ProtoTracklet_Eta_vtxZ_layer12')
    Draw_2Dhist(hM_dPhi_dEta_proto[0], False, False, 0.15, 'Proto-tracklet #Delta#phi', 'Proto-tracklet #Delta#eta', plotpath+'ProtoTracklet_dPhi_dEta_layer12')
    Draw_2Dhist(hM_dPhi_dEta_proto_altrange[0], True, False, 0.15, 'Proto-tracklet #Delta#phi', 'Proto-tracklet #Delta#eta', plotpath+'ProtoTracklet_dPhi_dEta_altrange_LogZ_layer12')
    Draw_2Dhist(hM_dPhi_dEta_proto_altrange[0], False, False, 0.15, 'Proto-tracklet #Delta#phi', 'Proto-tracklet #Delta#eta', plotpath+'ProtoTracklet_dPhi_dEta_altrange_LinZ_layer12')
    Draw_2Dhist(hM_Eta_vtxZ_reco[0], False, False, 0.14, 'Reco-tracklet #eta', 'Primary vertex V_{z} (cm)', plotpath+'RecoTracklet_Eta_vtxZ_layer12')
    Draw_2Dhist(hM_dPhi_dEta_reco[0], False, False, 0.13, 'Reco-tracklet #Delta#phi', 'Reco-tracklet #Delta#eta', plotpath+'RecoTracklet_dPhi_dEta_layer12')
    Draw_2Dhist(hM_dPhi_dEta_reco_altrange[0], True, False, 0.17, 'Reco-tracklet #Delta#phi', 'Reco-tracklet #Delta#eta', plotpath+'RecoTracklet_dPhi_dEta_altrange_LogZ_layer12')
    Draw_2Dhist(hM_dPhi_dEta_reco_altrange[0], False, False, 0.17, 'Reco-tracklet #Delta#phi', 'Reco-tracklet #Delta#eta', plotpath+'RecoTracklet_dPhi_dEta_altrange_LinZ_layer12')


if __name__ == '__main__':
    # misalignnum = 241
    misliannums = [0]
    for i in range(0, 40):
        misliannums.append((i*10) + 1)

    # for num in misliannums: 
    for num in [0]: 
        main(num)