Universe           = vanilla
Initialdir         = /sphenix/user/hjheng/TrackletAna/analysis
Executable         = $(Initialdir)/TrackletAna_condor.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 8GB
Priority           = 20
job_lease_duration = 3600
nEvents            = NEVENTS
skip               = SKIP 
layer              = LAYER
randhitcase        = RANDHITCASE
misalignnum        = MISALIGNNUM
Output             = $(Initialdir)/condor/condor_out/out/condor_layerLAYER_NevtNEVENTS_SkipSKIP_RandhitCaseRANDHITCASE_misalignnumMISALIGNNUM.out
Error              = $(Initialdir)/condor/condor_out/err/condor_layerLAYER_NevtNEVENTS_SkipSKIP_RandhitCaseRANDHITCASE_misalignnumMISALIGNNUM.err
Log                = $(Initialdir)/condor/condor_out/log/condor_layerLAYER_NevtNEVENTS_SkipSKIP_RandhitCaseRANDHITCASE_misalignnumMISALIGNNUM.log
Arguments          = $(nEvents) $(skip) $(layer) $(randhitcase) $(misalignnum)
Queue 1